// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubZ4QN7DOfgsIUZnCcWVp4aSZ4DgtgSg',
    appId: '1:170096254745:web:a11408e2e1281298e22f88',
    messagingSenderId: '170096254745',
    projectId: 'gymchimp-3bb5e',
    authDomain: 'gymchimp-3bb5e.firebaseapp.com',
    databaseURL: 'https://gymchimp-3bb5e-default-rtdb.firebaseio.com',
    storageBucket: 'gymchimp-3bb5e.appspot.com',
    measurementId: 'G-ZJXFN7806S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMl_Tw0K4yyAr7deGLgNV_LpZL2Jj9tY',
    appId: '1:170096254745:android:c67f59407afe52efe22f88',
    messagingSenderId: '170096254745',
    projectId: 'gymchimp-3bb5e',
    databaseURL: 'https://gymchimp-3bb5e-default-rtdb.firebaseio.com',
    storageBucket: 'gymchimp-3bb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCijZRhOeIcjeRJUtcy1hE6CK3WMyM58Ak',
    appId: '1:170096254745:ios:35391b178393f7afe22f88',
    messagingSenderId: '170096254745',
    projectId: 'gymchimp-3bb5e',
    databaseURL: 'https://gymchimp-3bb5e-default-rtdb.firebaseio.com',
    storageBucket: 'gymchimp-3bb5e.appspot.com',
    iosClientId: '170096254745-teu3a3lbp2k999jqjcao2pperpgcqgdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymchimp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCijZRhOeIcjeRJUtcy1hE6CK3WMyM58Ak',
    appId: '1:170096254745:ios:35391b178393f7afe22f88',
    messagingSenderId: '170096254745',
    projectId: 'gymchimp-3bb5e',
    databaseURL: 'https://gymchimp-3bb5e-default-rtdb.firebaseio.com',
    storageBucket: 'gymchimp-3bb5e.appspot.com',
    iosClientId: '170096254745-teu3a3lbp2k999jqjcao2pperpgcqgdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymchimp',
  );
}
