// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFsg8XRl3mYLKUlGzpTb7ncm91cTMG2Y',
    appId: '1:647270617312:web:6d93cfb54e10ac80728085',
    messagingSenderId: '647270617312',
    projectId: 'gymchimp-9e06e',
    authDomain: 'gymchimp-9e06e.firebaseapp.com',
    storageBucket: 'gymchimp-9e06e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXvZ3OTEgGnbRrrDgDQz8jbRMaW-fEEhw',
    appId: '1:647270617312:android:bdbc855878c80ffb728085',
    messagingSenderId: '647270617312',
    projectId: 'gymchimp-9e06e',
    storageBucket: 'gymchimp-9e06e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkgOwkbvC4C2DVPTTiCPGdR5yqAxPN8WA',
    appId: '1:647270617312:ios:6ebdc2c078ff18ae728085',
    messagingSenderId: '647270617312',
    projectId: 'gymchimp-9e06e',
    storageBucket: 'gymchimp-9e06e.appspot.com',
    iosClientId: '647270617312-u2a94dov6ab9i582c87uma6paalq7db2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymchimp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkgOwkbvC4C2DVPTTiCPGdR5yqAxPN8WA',
    appId: '1:647270617312:ios:6ebdc2c078ff18ae728085',
    messagingSenderId: '647270617312',
    projectId: 'gymchimp-9e06e',
    storageBucket: 'gymchimp-9e06e.appspot.com',
    iosClientId: '647270617312-u2a94dov6ab9i582c87uma6paalq7db2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymchimp',
  );
}
